### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Indigrep** [RaphRoss/Indesign_Translator#1]
Bonjour Raphaël,
J'ai découvert ton script via un tweet d'Indiscripts (Marc Autret). En définitive, je ne comprends pas les instructions décrites dans le ReadMe. J'ai installé Python. Quelles sont ensuite les étapes pour faire fonctionner le script ?
Merci
Laurent Tournier

**Comment by RaphRoss** [comment]
Bonjour Laurent,
Pour installer mon script et l'utiliser c'est très simple:
1. Sois tu l'installe via les commande git hub : "git clone git@github.com:RaphRoss/Indesign_Translator.git". Et tu lance le programme via la commande : "python main.py" (note qu'il faut que tu fasse la commande dans un terminal et que tu sois à l'endroit du script tu peut te déplacer dans ton terminal grace a la commande : "cd 'nom_du_dossier'")

2. Pour l'instant ce n'est qu'une beta mais en lien de ce retour je te met le .zip avec le .exe a l'intérieur ou tu aura juste a double clique dessus pour le lancer, il faut que tu sois sous windows pour cela.

J'espère que mon petit script t'aidera pour l'instant il y a encore beaucoup de fonctionnalité à venir alors n'hésite pas à revenir voir l'avancement !
Si jamais tu as d'autre question je suis à ta disposition !

Raphaël ROSSIGNOL

**Comment by RaphRoss** [comment]
[Uploading InDesign Translator.zip…]()

**Comment by Indigrep** [comment]
Bonjour Raphaël,
Merci pour ta réponse rapide et tes explications.
Faute de compétences pour les étapes 1 et 2, je suis passé directement à la phase 3. 
Le panneau s'ouvre correctement. J'ai tout renseigné, mais obtient deux messages d'erreur.
![Indesign Traduction](https://github.com/user-attachments/assets/1a51f2e2-2fa2-4455-b9aa-21cc93e0ddcc)
![Avertissement](https://github.com/user-attachments/assets/36d48337-ad36-4286-aa2a-3d55060e7642)
![Avertissement_02](https://github.com/user-attachments/assets/3a359c57-3d96-4dd5-8a77-b9c7edcb59b2)
Je suis sous InDesign CC 21 et Windows 11.
Ai-je manqué qqc ?

**Comment by RaphRoss** [comment]
Tu as effectivement manquer une étape mais je pense que c'est ma faute vue que je n'ai rien renseigner sur ce sujet.
Toute mes excuses !

Pour régler ce problème, je ne sais pas si tu l'a, mais quand on m'a demander de créé ce script on m'a toujours donné 2 choses :

1. Le fichier IDML à traduire
2. Un répertoire Temp contenant les informations sur le fichier IDML
<img width="509" alt="1screenshot" src="https://github.com/user-attachments/assets/ad9ca3ff-963d-4475-a04d-c1ce8680b354">
<img width="514" alt="2screenshot" src="https://github.com/user-attachments/assets/6d230067-d08f-40f3-8c5d-237b267420b9">

A l'intérieur de ce répertoire Temp se trouve le répertoire stories de ton erreur.
C'est grâce a ce répertoire "Stories" que j'envoie les requêtes XML au l'api DeepL
<img width="552" alt="3screenshot" src="https://github.com/user-attachments/assets/74bec7de-fdef-4b5d-a3a3-63416d0131fe">

Donc pour régler cette erreur il faut que ton répertoire Temp, contenant toute les informations, sois au même niveau que ton fichier IDML à traduire.

Malheureusement je ne sais pas comment créé se répertoire vue qu'il m'a été donné en l'état.
J'espère avoir pus t'aider !

**Comment by Indigrep** [comment]
OK. D'après ce que j'ai lu, un idml contient plusieurs fichiers XML, qui représentent un document InDesign complet. Les fichiers IDML sont stockés sous forme de package compressé à l'aide de la compression Zip? Je vais voir comment décompresser le fichiers pour les avoir. Il y a une méthode qui fonctionne pour un Word. Je te tiens au courant.
Encore merci

**Comment by Indigrep** [comment]
C'est tout simple. Il suffit de dézipper l'idml (j'utilise 7-Zip) et j'obtiens tous les dossiers, sauf Temp que je crée et dans lequel je place ensuite tous les autres. ET ça fonctionne super bien. Bravo.

**Comment by RaphRoss** [comment]
Merci Beaucoup pour ton retour je vais donc a l'avenir automatiser le dézippage du fichier IDML pour te simplifier la tâche !

Merci énormément de faire confiance à mon code c'est une première pour ma pars !
N'hésite pas à donner un étoile à mon repos pour lui donner de la visibilité et j'espère que les prochaines UPDATE de mon script pourrons te satisfaire !

Raphaël ROSSIGNOL
